name: 'Upload Event Types to Svix'
description: 'Upload Event Types from an OpenAPI spec to Svix'
inputs:
  openapi-file:
    description: 'Location of the OpenAPI spec file'
    required: true
  svix-api-key:
    description: 'Svix API key'
    required: true
  svix-region:
    description: 'Svix region: us or eu'
    required: false
    default: 'us'
runs:
  using: "composite"
  steps:
    - name: Upload OpenAPI spec to Svix
      run: |
        RAW_SPEC=$(cat ${{inputs.openapi-file}} | jq -Rs)
        curl -X 'POST' 'https://api.${{inputs.svix-region}}.svix.com/api/v1/event-type/import/openapi/' \
            -H 'Authorization: Bearer ${{ inputs.svix-api-key }}' \
            --json "{\"specRaw\": $RAW_SPEC}"
      shell: bash